/* The following code was generated by JFlex 1.3.5 on 20/10/15 14:33 */

package cup.example;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.lang.*;
import java.io.InputStreamReader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 20/10/15 14:33 from the specification file
 * <tt>file:/C:/Users/Marcia Cavalcante/workspace/Analisador/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 0;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\2\3\2\0\1\3\22\0\1\3\1\51\3\0\1\54\1\47"+
    "\1\0\1\40\1\41\1\2\1\7\1\56\1\6\1\11\1\1\1\5"+
    "\11\10\1\0\1\55\1\52\1\50\1\53\2\0\4\4\1\12\25\4"+
    "\1\44\1\0\1\45\1\0\1\4\1\0\1\17\1\14\1\21\1\23"+
    "\1\13\1\26\1\37\1\34\1\30\2\4\1\16\1\36\1\20\1\15"+
    "\1\32\1\4\1\27\1\22\1\25\1\33\1\35\1\31\1\24\2\4"+
    "\1\42\1\46\1\43\uff82\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    47,    94,    94,   141,   188,   235,   235,   282,    94, 
      329,   376,   423,   470,   517,   564,   611,   658,   705,   752, 
      799,   846,   893,   940,   987,    94,    94,    94,    94,    94, 
       94,  1034,  1081,  1128,  1175,  1222,  1269,    94,    94,    94, 
     1316,  1363,  1410,  1457,  1504,  1551,  1598,  1645,  1692,   141, 
     1739,  1786,  1833,  1880,  1927,  1974,   141,  2021,  2068,  2115, 
     2162,    94,    94,    94,    94,    94,    94,  2209,  2256,  2303, 
     2350,  2397,  2444,   141,  2491,  2538,  2585,  2632,  2679,   141, 
     2726,  2773,   141,  2820,  2867,  2914,  2961,    94,  3008,   141, 
     3055,  3102,  3149,  3196,  3243,  3290,   141,   141,  3337,  3384, 
     3431,  3478,   141,   141,    94,  3525,  3572,  3619,  3666,  3713, 
      141,  3760,  3807,   141,  3854,   141,  3901,  3948,  3995,   141, 
      141,   141,   141,   141,   141,   141
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\0\1\2\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\5\1\13\1\14\1\5\1\15\1\5"+
    "\1\16\1\17\1\20\1\21\1\5\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\2\5\1\30\1\31\1\5\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\2\0\1\51"+
    "\137\0\2\5\2\0\1\5\1\0\26\5\30\0\1\52"+
    "\52\0\1\6\2\0\1\11\53\0\1\11\2\0\1\11"+
    "\1\52\51\0\2\5\2\0\1\5\1\0\4\5\1\53"+
    "\5\5\1\54\13\5\23\0\2\5\2\0\1\5\1\0"+
    "\3\5\1\55\22\5\23\0\2\5\2\0\1\5\1\0"+
    "\1\5\1\56\24\5\23\0\2\5\2\0\1\5\1\0"+
    "\1\5\1\57\24\5\23\0\2\5\2\0\1\5\1\0"+
    "\4\5\1\60\21\5\23\0\2\5\2\0\1\5\1\0"+
    "\13\5\1\61\12\5\23\0\2\5\2\0\1\5\1\0"+
    "\3\5\1\62\22\5\23\0\2\5\2\0\1\5\1\0"+
    "\15\5\1\63\4\5\1\64\3\5\23\0\2\5\2\0"+
    "\1\5\1\0\3\5\1\65\1\5\1\66\20\5\23\0"+
    "\2\5\2\0\1\5\1\0\1\5\1\67\24\5\23\0"+
    "\2\5\2\0\1\5\1\0\6\5\1\70\5\5\1\71"+
    "\11\5\23\0\2\5\2\0\1\5\1\0\22\5\1\72"+
    "\3\5\23\0\2\5\2\0\1\5\1\0\21\5\1\73"+
    "\4\5\23\0\2\5\2\0\1\5\1\0\3\5\1\74"+
    "\22\5\23\0\2\5\2\0\1\5\1\0\5\5\1\75"+
    "\20\5\65\0\1\76\57\0\1\77\57\0\1\100\56\0"+
    "\1\101\56\0\1\102\56\0\1\103\6\0\2\51\1\104"+
    "\54\51\5\0\1\105\2\0\1\105\52\0\2\5\2\0"+
    "\1\5\1\0\10\5\1\106\15\5\23\0\2\5\2\0"+
    "\1\5\1\0\13\5\1\107\12\5\23\0\2\5\2\0"+
    "\1\5\1\0\3\5\1\110\22\5\23\0\2\5\2\0"+
    "\1\5\1\0\6\5\1\111\17\5\23\0\2\5\2\0"+
    "\1\5\1\0\17\5\1\112\6\5\23\0\2\5\2\0"+
    "\1\5\1\0\5\5\1\113\20\5\23\0\2\5\2\0"+
    "\1\5\1\0\5\5\1\114\7\5\1\115\10\5\23\0"+
    "\2\5\2\0\1\5\1\0\21\5\1\116\4\5\23\0"+
    "\2\5\2\0\1\5\1\0\16\5\1\117\7\5\23\0"+
    "\2\5\2\0\1\5\1\0\15\5\1\120\10\5\23\0"+
    "\2\5\2\0\1\5\1\0\4\5\1\121\21\5\23\0"+
    "\2\5\2\0\1\5\1\0\13\5\1\122\12\5\23\0"+
    "\2\5\2\0\1\5\1\0\13\5\1\123\12\5\23\0"+
    "\2\5\2\0\1\5\1\0\16\5\1\124\7\5\23\0"+
    "\2\5\2\0\1\5\1\0\2\5\1\125\23\5\23\0"+
    "\2\5\2\0\1\5\1\0\16\5\1\126\7\5\23\0"+
    "\2\5\2\0\1\5\1\0\16\5\1\127\7\5\17\0"+
    "\1\51\1\130\1\104\54\51\5\0\1\105\2\0\1\105"+
    "\1\0\2\131\47\0\2\5\2\0\1\5\1\0\1\5"+
    "\1\132\24\5\23\0\2\5\2\0\1\5\1\0\1\5"+
    "\1\133\24\5\23\0\2\5\2\0\1\5\1\0\4\5"+
    "\1\134\21\5\23\0\2\5\2\0\1\5\1\0\25\5"+
    "\1\135\23\0\2\5\2\0\1\5\1\0\10\5\1\136"+
    "\15\5\23\0\2\5\2\0\1\5\1\0\13\5\1\137"+
    "\12\5\23\0\2\5\2\0\1\5\1\0\16\5\1\140"+
    "\7\5\23\0\2\5\2\0\1\5\1\0\1\5\1\141"+
    "\24\5\23\0\2\5\2\0\1\5\1\0\10\5\1\142"+
    "\15\5\23\0\2\5\2\0\1\5\1\0\10\5\1\143"+
    "\15\5\23\0\2\5\2\0\1\5\1\0\21\5\1\144"+
    "\4\5\23\0\2\5\2\0\1\5\1\0\4\5\1\145"+
    "\21\5\23\0\2\5\2\0\1\5\1\0\4\5\1\146"+
    "\21\5\23\0\2\5\2\0\1\5\1\0\11\5\1\147"+
    "\14\5\23\0\2\5\2\0\1\5\1\0\6\5\1\150"+
    "\17\5\24\0\1\151\2\152\1\153\52\0\2\5\2\0"+
    "\1\5\1\0\6\5\1\154\17\5\23\0\2\5\2\0"+
    "\1\5\1\0\1\5\1\155\24\5\23\0\2\5\2\0"+
    "\1\5\1\0\13\5\1\156\12\5\23\0\2\5\2\0"+
    "\1\5\1\0\10\5\1\157\15\5\23\0\2\5\2\0"+
    "\1\5\1\0\16\5\1\160\7\5\23\0\2\5\2\0"+
    "\1\5\1\0\6\5\1\161\17\5\23\0\2\5\2\0"+
    "\1\5\1\0\1\5\1\162\24\5\23\0\2\5\2\0"+
    "\1\5\1\0\15\5\1\163\10\5\23\0\2\5\2\0"+
    "\1\5\1\0\1\5\1\164\24\5\23\0\2\5\2\0"+
    "\1\5\1\0\16\5\1\165\7\5\24\0\1\151\2\0"+
    "\1\153\53\0\1\153\2\0\1\153\52\0\2\5\2\0"+
    "\1\5\1\0\11\5\1\166\14\5\23\0\2\5\2\0"+
    "\1\5\1\0\5\5\1\167\20\5\23\0\2\5\2\0"+
    "\1\5\1\0\22\5\1\170\3\5\23\0\2\5\2\0"+
    "\1\5\1\0\7\5\1\171\16\5\23\0\2\5\2\0"+
    "\1\5\1\0\25\5\1\172\23\0\2\5\2\0\1\5"+
    "\1\0\6\5\1\173\17\5\23\0\2\5\2\0\1\5"+
    "\1\0\7\5\1\174\16\5\23\0\2\5\2\0\1\5"+
    "\1\0\10\5\1\175\15\5\23\0\2\5\2\0\1\5"+
    "\1\0\6\5\1\176\17\5\17\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  1,  9,  9,  1,  1,  1,  1,  1,  9,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  9,  9,  9,  9,  9,  0, 
     0,  1,  1,  1,  1,  9,  9,  9,  0,  0,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  9,  9, 
     9,  9,  9,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  9,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	

    public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
		this(is);
        symbolFactory = sf;
    }
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar), // -yylength()
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    public Symbol symbol(String name, int code, String lexem){
	return symbolFactory.newSymbol(name, code, 
						new Location(yyline+1, yycolumn +1, yychar), 
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), lexem);
    }
    
    protected void emit_warning(String message){
    	System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    	System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[4042];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 128) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 5: 
        case 8: 
          {  return symbolFactory.newSymbol(yytext(), INTEGER, Integer.parseInt(yytext()));  }
        case 127: break;
        case 68: 
        case 88: 
        case 104: 
        case 105: 
        case 106: 
          {  return symbolFactory.newSymbol(yytext(), FLOAT, Float.parseFloat(yytext()));  }
        case 128: break;
        case 125: 
          {  return symbolFactory.newSymbol(yytext(), BOOLEAN);  }
        case 129: break;
        case 124: 
          {  return symbolFactory.newSymbol(yytext(), EXTENDS);  }
        case 130: break;
        case 103: 
          {  return symbolFactory.newSymbol(yytext(), MAIN);  }
        case 131: break;
        case 102: 
          {  return symbolFactory.newSymbol(yytext(), VOID);  }
        case 132: break;
        case 97: 
          {  return symbolFactory.newSymbol(yytext(), THIS);  }
        case 133: break;
        case 96: 
          {  return symbolFactory.newSymbol(yytext(), TRUE);  }
        case 134: break;
        case 34: 
          {  return symbolFactory.newSymbol(yytext(), NOT);  }
        case 135: break;
        case 33: 
          {  return symbolFactory.newSymbol(yytext(), ATB);  }
        case 136: break;
        case 1: 
          {  return symbolFactory.newSymbol(yytext(), DIV);  }
        case 137: break;
        case 7: 
          {  return symbolFactory.newSymbol(yytext(), PLUS);  }
        case 138: break;
        case 9: 
          {  return symbolFactory.newSymbol(yytext(), DOT);  }
        case 139: break;
        case 37: 
          {  return symbolFactory.newSymbol(yytext(), MOD);  }
        case 140: break;
        case 38: 
          {  return symbolFactory.newSymbol(yytext(), SEMI);  }
        case 141: break;
        case 62: 
          {  return symbolFactory.newSymbol(yytext(), AND);  }
        case 142: break;
        case 64: 
          {  return symbolFactory.newSymbol(yytext(), NEQ);  }
        case 143: break;
        case 65: 
          {  return symbolFactory.newSymbol(yytext(), LEQ);  }
        case 144: break;
        case 66: 
          {  return symbolFactory.newSymbol(yytext(), GEQ);  }
        case 145: break;
        case 73: 
          {  return symbolFactory.newSymbol(yytext(), NEW);  }
        case 146: break;
        case 79: 
          {  return symbolFactory.newSymbol(yytext(), FOR);  }
        case 147: break;
        case 82: 
          {  return symbolFactory.newSymbol(yytext(), INT);  }
        case 148: break;
        case 89: 
          {  return symbolFactory.newSymbol(yytext(), ELSE);  }
        case 149: break;
        case 35: 
          {  return symbolFactory.newSymbol(yytext(), LT);  }
        case 150: break;
        case 36: 
          {  return symbolFactory.newSymbol(yytext(), GT);  }
        case 151: break;
        case 49: 
          {  return symbolFactory.newSymbol(yytext(), DO);  }
        case 152: break;
        case 56: 
          {  return symbolFactory.newSymbol(yytext(), IF);  }
        case 153: break;
        case 61: 
          {  return symbolFactory.newSymbol(yytext(), OR);  }
        case 154: break;
        case 63: 
          {  return symbolFactory.newSymbol(yytext(), EQ);  }
        case 155: break;
        case 87: 
          { /*NADINNHA*/ }
        case 156: break;
        case 4: 
        case 10: 
        case 11: 
        case 12: 
        case 13: 
        case 14: 
        case 15: 
        case 16: 
        case 17: 
        case 18: 
        case 19: 
        case 20: 
        case 21: 
        case 22: 
        case 23: 
        case 24: 
        case 42: 
        case 43: 
        case 44: 
        case 45: 
        case 46: 
        case 47: 
        case 48: 
        case 50: 
        case 51: 
        case 52: 
        case 53: 
        case 54: 
        case 55: 
        case 57: 
        case 58: 
        case 59: 
        case 60: 
        case 69: 
        case 70: 
        case 71: 
        case 72: 
        case 74: 
        case 75: 
        case 76: 
        case 77: 
        case 78: 
        case 80: 
        case 81: 
        case 83: 
        case 84: 
        case 85: 
        case 86: 
        case 90: 
        case 91: 
        case 92: 
        case 93: 
        case 94: 
        case 95: 
        case 98: 
        case 99: 
        case 100: 
        case 101: 
        case 107: 
        case 108: 
        case 109: 
        case 111: 
        case 112: 
        case 114: 
        case 116: 
        case 117: 
        case 118: 
          { return symbolFactory.newSymbol(yytext(), ID, yytext()); }
        case 157: break;
        case 123: 
          {  return symbolFactory.newSymbol(yytext(), PUBLIC);  }
        case 158: break;
        case 122: 
          {  return symbolFactory.newSymbol(yytext(), RETURN);  }
        case 159: break;
        case 121: 
          {  return symbolFactory.newSymbol(yytext(), STRING);  }
        case 160: break;
        case 120: 
          {  return symbolFactory.newSymbol(yytext(), STATIC);  }
        case 161: break;
        case 119: 
          {  return symbolFactory.newSymbol(yytext(), LENGTH);  }
        case 162: break;
        case 115: 
          {  return symbolFactory.newSymbol(yytext(), WHILE);  }
        case 163: break;
        case 113: 
          {  return symbolFactory.newSymbol(yytext(), FALSE);  }
        case 164: break;
        case 110: 
          {  return symbolFactory.newSymbol(yytext(), CLASS);  }
        case 165: break;
        case 30: 
          {  return symbolFactory.newSymbol(yytext(), R_CON);  }
        case 166: break;
        case 29: 
          {  return symbolFactory.newSymbol(yytext(), L_CON);  }
        case 167: break;
        case 28: 
          {  return symbolFactory.newSymbol(yytext(), R_CHA);  }
        case 168: break;
        case 27: 
          {  return symbolFactory.newSymbol(yytext(), L_CHA);  }
        case 169: break;
        case 26: 
          {  return symbolFactory.newSymbol(yytext(), R_PARE);  }
        case 170: break;
        case 25: 
          {  return symbolFactory.newSymbol(yytext(), L_PARE);  }
        case 171: break;
        case 2: 
          {  return symbolFactory.newSymbol(yytext(), TIMES);  }
        case 172: break;
        case 3: 
          { /*NADA */ }
        case 173: break;
        case 6: 
          {  return symbolFactory.newSymbol(yytext(), MINUS);  }
        case 174: break;
        case 39: 
          {  return symbolFactory.newSymbol(yytext(), COMMA);  }
        case 175: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
