
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int L_PARE = 19;
  public static final int R_PARE = 20;
  public static final int INTEGER = 42;
  public static final int SEMI = 39;
  public static final int R_CON = 24;
  public static final int INT = 10;
  public static final int FOR = 8;
  public static final int MINUS = 34;
  public static final int L_CHA = 21;
  public static final int STATIC = 14;
  public static final int NOT = 38;
  public static final int AND = 26;
  public static final int LT = 29;
  public static final int OR = 25;
  public static final int ATB = 41;
  public static final int CLASS = 3;
  public static final int DIV = 36;
  public static final int GEQ = 32;
  public static final int PLUS = 33;
  public static final int IF = 9;
  public static final int THIS = 15;
  public static final int ID = 44;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 13;
  public static final int TRUE = 16;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int MOD = 37;
  public static final int NEQ = 28;
  public static final int R_CHA = 22;
  public static final int VOID = 17;
  public static final int EQ = 27;
  public static final int TIMES = 35;
  public static final int ELSE = 5;
  public static final int WHILE = 18;
  public static final int FLOAT = 43;
  public static final int PUBLIC = 12;
  public static final int EXTENDS = 6;
  public static final int LEQ = 30;
  public static final int L_CON = 23;
  public static final int FALSE = 7;
  public static final int GT = 31;
  public static final int DO = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "CLASS",
  "DO",
  "ELSE",
  "EXTENDS",
  "FALSE",
  "FOR",
  "IF",
  "INT",
  "NEW",
  "PUBLIC",
  "RETURN",
  "STATIC",
  "THIS",
  "TRUE",
  "VOID",
  "WHILE",
  "L_PARE",
  "R_PARE",
  "L_CHA",
  "R_CHA",
  "L_CON",
  "R_CON",
  "OR",
  "AND",
  "EQ",
  "NEQ",
  "LT",
  "LEQ",
  "GT",
  "GEQ",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "NOT",
  "SEMI",
  "DOT",
  "ATB",
  "INTEGER",
  "FLOAT",
  "ID"
  };
}

